import { AnyModel, createModelMapper, GeneratedModelMapper } from '@raynode/graphql-connector'
import * as Sequelize from 'sequelize'
import { DataTypes } from './type-guards'

// somehow the sequelize types are really really bad!

export interface SequelizeAttributeReference {
  model: string
  key: string
}

export interface SequelizeAttribute {
  _autoGenerated?: boolean
  type: DataTypes
  allowNull: boolean
  primaryKey?: boolean
  comment: string
  references?: SequelizeAttributeReference
}

export type SequelizeAssociationTypes = 'HasOne' | 'HasMany' | 'BelongsTo' | 'BelongsToMany'

export interface SequelizeAssociation {
  source: SequelizeModel
  target: SequelizeModel
  as: string
  associationType: SequelizeAssociationTypes
  foreignKeyAttribute: string
  foreignKey: string
  identifier: string
  targetKey: string
  targetKeyField: string
  targetKeyIsPrimary: string
  targetIdentifier: string
  accessors: string
  identifierField: string
}

export interface SequelizeModel extends Sequelize.Model<any, any> {
  rawAttributes: Record<string, SequelizeAttribute>
  associations: Record<string, SequelizeAssociation>
}

export interface Models {
  [x: string]: Sequelize.Model<any, any>
}

export const modelMapper = createModelMapper<DataTypes, Models>((model, addAttribute, addAssociation) => {
  const rawModel: SequelizeModel = model as any
  Object.keys(rawModel.rawAttributes).forEach(name => {
    const attribute = rawModel.rawAttributes[name]
    // console.log(JSON.stringify(attribute, null, 2))
    addAttribute({
      name,
      type: attribute.type,
      nonNull: attribute.allowNull === false || attribute.primaryKey === true,
      resolver: instance => instance[name],
      // changable: !(attribute._autoGenerated || attribute.primaryKey || attribute.references),
    })
  })

  Object.keys(rawModel.associations).forEach(name => {
    const association = rawModel.associations[name]
    addAssociation({
      name: association.as,
      model: association.target.name,
      list: association.associationType === 'HasMany' || association.associationType === 'BelongsToMany',
      nonNull: association.associationType === 'BelongsTo' || association.associationType === 'BelongsToMany',
      resolver: async (instance, args, context, info) => {
        // console.log(info.fieldName, info.fieldNodes)
        // console.log(rawModel, association)
        // console.log(`get${association.as}`, instance[`get${association.as}`])
        return instance[`get${association.as}`]()
      },
    })
  })

  return {
    create: async (_, { data }) => model.create(data),
    delete: async () => null,
    findMany: async (_, { order, where, page = {
      limit: 100,
      offset: 0,
    }}) => {
      console.log('FIND MANY', where, page, order)
      const { count, rows: nodes } = await model.findAndCountAll({ where, order })
      return {
        nodes,
        page,
      }
    },
    findOne: async () => null,
    update: async () => null,
  }
})
